@GeoNet/db/Triggers/pm_info_BU_ROW.sql
@GeoNet/db/Triggers/pm_info_AU_ROW.sql
@GeoNet/db/Triggers/tids_to_update_view_IOU.sql
@GeoNet/db/Triggers/Ack_Alarms_View_IOU.sql
@GeoNet/db/Triggers/facility_keephistory_AU_Row.sql
@GeoNet/db/Triggers/pnni_historical_AI_ROW.sql
@GeoNet/db/Triggers/pnni_historical_AU_ROW.sql
@GeoNet/db/Triggers/pnni_switchinfo_AI_ROW.sql
@GeoNet/db/Triggers/pnni_historical_AIU_ROW.sql
@GeoNet/db/Triggers/tid_interface_status_BU_ROW.sql
@GeoNet/db/Triggers/tid_interface_status_AU_ROW.sql
@GeoNet/db/Triggers/tid_interface_status_AU_STM.sql
@GeoNet/db/Triggers/tid_keephistory_AU_ROW.sql
