<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="image" src="https://www.paypal.com/en_US/i/btn/x-click-but24.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
<input type="hidden" name="cmd" value="_xclick-subscriptions">
<input type="hidden" name="business" value="sales@shopandbuzz.com">
<input type="hidden" name="item_name" value="Shop and Buzz Subscription">
<input type="hidden" name="item_number" value="sandbsub">
<input type="hidden" name="no_shipping" value="1">
<input type="hidden" name="return" value="http://www.shopandbuzz.com/payments/pmt_thank_you.php">
<input type="hidden" name="cancel_return" value="http://www.shopandbuzz.com/payments/sub_cancel.php">
<input type="hidden" name="no_note" value="1">
<input type="hidden" name="currency_code" value="USD">
<input type="hidden" name="lc" value="US">
<input type="hidden" name="bn" value="PP-SubscriptionsBF">
<input type="hidden" name="a1" value="0.00">
<input type="hidden" name="p1" value="1">
<input type="hidden" name="t1" value="M">
<input type="hidden" name="a3" value="27.00">
<input type="hidden" name="p3" value="2">
<input type="hidden" name="t3" value="M">
<input type="hidden" name="src" value="1">
<input type="hidden" name="sra" value="1">
</form>
