CREATE OR REPLACE FUNCTION shift_tid_queue
( xtid IN tids.id%TYPE )
RETURN NUMBER
AS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  DELETE FROM tid_queue WHERE tid_id = xtid;
  COMMIT;
  RETURN 0;
END;  
/
SHOW ERRORS
