-- log in as system
CREATE USER "PNNI_USERS"  PROFILE "DEFAULT" IDENTIFIED BY 
    "pnni_users" DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "PNNI_USERS";
    
-- log in as geonet    
GRANT DELETE ON "GEONET"."HISTORICAL" TO "PNNI_USERS";
GRANT DELETE ON "GEONET"."IPCONVERSION" TO "PNNI_USERS";
GRANT DELETE ON "GEONET"."PORTCONVERSION" TO "PNNI_USERS";
GRANT DELETE ON "GEONET"."SWITCHINFO" TO "PNNI_USERS";
GRANT INSERT ON "GEONET"."HISTORICAL" TO "PNNI_USERS";
GRANT INSERT ON "GEONET"."IPCONVERSION" TO "PNNI_USERS";
GRANT INSERT ON "GEONET"."PORTCONVERSION" TO "PNNI_USERS";
GRANT INSERT ON "GEONET"."SWITCHINFO" TO "PNNI_USERS";
GRANT SELECT ON "GEONET"."HISTORICAL" TO "PNNI_USERS";
GRANT SELECT ON "GEONET"."IPCONVERSION" TO "PNNI_USERS";
GRANT SELECT ON "GEONET"."PORTCONVERSION" TO "PNNI_USERS";
GRANT SELECT ON "GEONET"."SWITCHINFO" TO "PNNI_USERS";
GRANT UPDATE ON "GEONET"."HISTORICAL" TO "PNNI_USERS";
GRANT UPDATE ON "GEONET"."IPCONVERSION" TO "PNNI_USERS";
GRANT UPDATE ON "GEONET"."PORTCONVERSION" TO "PNNI_USERS";
GRANT UPDATE ON "GEONET"."SWITCHINFO" TO "PNNI_USERS";
