@GeoNet/db/Tables/Table_Creation.sql
@GeoNet/db/Indexes/Index_Creation.sql
@GeoNet/db/Packages/Package_Creation.sql
@GeoNet/db/Procedures/Procedure_Creation.sql
@GeoNet/db/Views/View_Creation.sql
@GeoNet/db/Triggers/Trigger_Creation.sql
@GeoNet/db/DatabaseLinks/DatabaseLink_Creation.sql
@GeoNet/db/Sequences/Sequence_Creation.sql
@GeoNet/db/Basic_Data_Creation.sql