-- historical
-- pnni table

CREATE TABLE HISTORICAL (
    PATHINDEX NUMBER(8), 
    CUSTOMER VARCHAR2(100), 
    CURRENTPATH NUMBER(1), 
    TIMECHANGED VARCHAR2(14), 
    TIMEUPDATED VARCHAR2(14), 
    CONNECTION VARCHAR2(50), 
    CONNECTIONTYPE VARCHAR2(15), 
    HOP NUMBER(3), 
    INPORT VARCHAR2(10), 
    INVP NUMBER(8), 
    INVC NUMBER(8), 
    CLLI VARCHAR2(15), 
    OUTPORT VARCHAR2(10), 
    OUTVP NUMBER(8), 
    OUTVC NUMBER(8), 
    INPORTINPUTUTIL NUMBER(3), 
    INPORTOUTPUTUTIL NUMBER(3), 
    OUTPORTINPUTUTIL NUMBER(3), 
    OUTPORTOUTPUTUTIL NUMBER(3), 
    INPORTINPUTALLOCATEDBW VARCHAR2(50), 
    INPORTOUTPUTALLOCATEDBW VARCHAR2(50), 
    OUTPORTINPUTALLOCATEDBW VARCHAR2(50), 
    OUTPORTOUTPUTALLOCATEDBW VARCHAR2(50), 
    INPORTATMRATE VARCHAR2(50), 
    OUTPORTATMRATE VARCHAR2(50), 
    NVCID VARCHAR2(15), 
    FMSCIRCUITID NUMBER(10), 
    CITYPAIR VARCHAR2(9), 
    DETAILS VARCHAR2(500),
    TRACENUM  NUMBER(8),
    NSAP VARCHAR2(40) 
);
-- link to pnni.historical on the ntacdata server is historical_old
-- insert into historical select * from pnni.historical@ntacdata;
