@GeoNet/db/Tables/debugging_Table_Def.sql
@GeoNet/db/Tables/customer_types_Table_Def.sql
@GeoNet/db/Tables/user_groups_Table_Def.sql
@GeoNet/db/Tables/security_levels_Table_Def.sql
@GeoNet/db/Tables/Speeds_Table_Def.sql
@GeoNet/db/Tables/cities_Table_Def.sql
@GeoNet/db/Tables/receive_channels_Table_Def.sql
@GeoNet/db/Tables/protocols_Table_Def.sql
@GeoNet/db/Tables/users_Table_Def.sql
@GeoNet/db/Tables/element_types_Table_Def.sql
@GeoNet/db/Tables/customers_Table_Def.sql
@GeoNet/db/Tables/facilities_Table_Def.sql
@GeoNet/db/Tables/tids_Table_Def.sql
@GeoNet/db/Tables/interface_types_Table_Def.sql
@GeoNet/db/Tables/interfaces_Table_Def.sql
@GeoNet/db/Tables/customer_group_map_Table_Def.sql
@GeoNet/db/Tables/user_group_user_map_Table_Def.sql
@GeoNet/db/Tables/tid_interface_status_Table_Def.sql
@GeoNet/db/Tables/tid_facility_map_Table_Def.sql
@GeoNet/db/Tables/tid_queue_Table_Def.sql
@GeoNet/db/Tables/fiber_routes_Table_Def.sql
@GeoNet/db/Tables/fiber_segments_Table_Def.sql
@GeoNet/db/Tables/scheduled_outages_Table_Def.sql
@GeoNet/db/Tables/alarms_Table_Def.sql
@GeoNet/db/Tables/pm_info_Table_Def.sql
@GeoNet/db/Tables/pm_history_Table_Def.sql
@GeoNet/db/Tables/historical_Table_Def.sql
@GeoNet/db/Tables/ipconversion_Table_Def.sql
@GeoNet/db/Tables/portconversion_Table_Def.sql
@GeoNet/db/Tables/switchinfo_Table_Def.sql
@GeoNet/db/Tables/Facility_Associations_Table_Def.sql
@GeoNet/db/Tables/speed_equivalent_map_Table_Def.sql
@GeoNet/db/Tables/outage_procedure_Table_Def.sql
@GeoNet/db/Tables/proc_customer_map_Table_Def.sql
